#cloud-config
write_files:
  - path: /etc/docker/daemon.json
    permissions: "0644"
    owner: root
    content: |
      { "features": { "buildkit": true } }

  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash

      iptables -I DOCKER-USER -i dns -j ACCEPT
      iptables -I DOCKER-USER -o dns -j ACCEPT

      # mkdir /Users
      # mount --bind /Users /Users
      # mount --make-shared /Users
      mkdir -p /usr/src

      cat > /etc/ssh/sshd_config <<EOM
      AuthorizedKeysFile .ssh/authorized_keys
      Subsystem sftp /usr/libexec/sftp-server
      UseDNS no
      PermitRootLogin no
      AllowGroups docker

      # We include dh-sha1 here for fsevents
      KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha1
      Protocol 2
      HostKey /etc/ssh/ssh_host_ed25519_key
      # Include rsa host key for fsevents
      HostKey /etc/ssh/ssh_host_rsa_key

      PasswordAuthentication no
      ChallengeResponseAuthentication no
      PubkeyAuthentication yes
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
      EOM

      wait-for-docker

      docker network create \
        --driver=bridge --subnet=10.10.10.0/24 --ip-range=10.10.10.1/30 \
        -o com.docker.network.bridge.enable_icc=true \
        -o com.docker.network.bridge.enable_ip_masquerade=true \
        -o com.docker.network.bridge.name=dns \
        dns

        INSTANCE_IP=$(ip -o -4 -br addr show eth0 | awk '{print $3}' | cut -d/ -f1)
        iptables -t nat -A PREROUTING -p tcp -d 127.0.0.1 --dport 8400 -j DNAT --to ${INSTANCE_IP}
        iptables -t nat -A PREROUTING -p tcp -d 127.0.0.1 --dport 8500 -j DNAT --to ${INSTANCE_IP}
        iptables -t nat -A OUTPUT -o lo -p tcp -m tcp --dport 8400 -j DNAT --to ${INSTANCE_IP}
        iptables -t nat -A OUTPUT -o lo -p tcp -m tcp --dport 8500 -j DNAT --to ${INSTANCE_IP}

rancher:
  sysctl:
    vm.max_map_count: 262144
  docker:
    config_file: /etc/docker/daemon.json
