consul:
  image: consul:1.5.3
  restart: always
  labels:
    - io.rancher.os.remove=false
  net: host
  command: agent -dev -ui
  environment:
    CONSUL_BIND_INTERFACE: eth0
    CONSUL_CLIENT_INTERFACE: eth0
